# Generated by Django 4.1.7 on 2023-05-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20230524_1659'),
        ('pybo', '0008_questionhistory_answerhistory'),
    ]

    operations = [
    ]
